version: "3.9"
services:
  backend: 
    build:
      context: ./python
      dockerfile: Dockerfile
    #image: "build2024/app:latest"
    ports:
      - "9000:9000"
    environment:
      FRONT_URL: "http://localhost:3000"


  frontend: 
    build:
      context: ./typescript/simple-mercari-web
      dockerfile: Dockerfile
    #image: "build2024/web:latest"
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: "http://localhost:9000/" 
  