#syntax=docker/dockerfile:1
FROM node:20-alpine

WORKDIR /app

# image内にソースコードをコピー (typescript/simple-mercari-web でbuildするから)
COPY package*.json ./
COPY tsconfig.json ./
COPY . .

RUN npm install

EXPOSE 3000


RUN addgroup -S mercari && adduser -S trainee -G mercari
RUN chown -R trainee:mercari /app
USER trainee


CMD ["npm", "start"]
