#syntax=docker/dockerfile:1
FROM node:20-alpine
WORKDIR /app

# image内にソースコードをコピー (typescript/simple-mercari-web でbuildするから)
COPY . .

RUN npm install

EXPOSE 3000

RUN addgroup -S mercari && adduser -S trainee -G mercari
USER trainee

CMD ["npm", "start"]
