#syntax=docker/dockerfile:1
#FROM python:3.10-alpine
FROM python:3.8-slim-buster

#RUN addgroup -S mercari && adduser -S trainee -G mercari

WORKDIR /app


# Pythonとcurlのinstall
COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt
RUN apt-get update && apt-get install -y curl

# image内にソースコードをコピー
#COPY db /app/db
COPY . .

# このportで実行
EXPOSE 9000

#RUN chown -R trainee:mercari /app/python
#USER trainee

# API有効化する
CMD ["uvicorn", "main:app", "--host", "127.0.0.1", "--port", "9000"]

# python のバージョン確認
#CMD ["python", "-V"]


#FROM alpine

#RUN addgroup -S mercari && adduser -S trainee -G mercari
# RUN chown -R trainee:mercari /path/to/db

#USER trainee



