#syntax=docker/dockerfile:1
FROM python:3.8-slim-buster

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt
RUN apt-get update && apt-get install -y curl

COPY . .

EXPOSE 9000

#CMD ["python", "-V"] 
# python のバージョン確認

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "9000"]
# API有効化する
# RUNNING になる



#FROM alpine

#RUN addgroup -S mercari && adduser -S trainee -G mercari
# RUN chown -R trainee:mercari /path/to/db

#USER trainee



